d = [
     {
          "name": "id",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "ID",
          "cn": "ID",
          "zh_TW": "ID",
          "label_value": "ID"
     },
     {
          "name": "type",
          "type": "char",
          "view_type": "radio",
          "options": [
               {
                    "type": "candidate_type",
                    "code": "candidate",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Candidate",
                    "zh_CN": "候选人",
                    "zh_TW": None,
                    "color": "#08c",
                    "order": 1,
                    "id": 436,
                    "value": "候选人",
                    "__name__": "候选人",
                    "__unicode__": "候选人"
               },
               {
                    "type": "candidate_type",
                    "code": "contact",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Contact",
                    "zh_CN": "联系人",
                    "zh_TW": None,
                    "color": "#FF6666",
                    "order": 2,
                    "id": 437,
                    "value": "联系人",
                    "__name__": "联系人",
                    "__unicode__": "联系人"
               },
               {
                    "type": "candidate_type",
                    "code": "coldcall",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Cold Call",
                    "zh_CN": "Cold Call",
                    "zh_TW": None,
                    "color": "#999999",
                    "order": 3,
                    "id": 438,
                    "value": "Cold Call",
                    "__name__": "Cold Call",
                    "__unicode__": "Cold Call"
               }
          ],
          "option_key": "candidate_type",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "is_record_type_key": True,
          "en": "Type",
          "cn": "类型",
          "zh_TW": "類型",
          "label_value": "类型"
     },
     {
          "name": "is_mpc",
          "type": "boolean",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "MPC",
          "cn": "MPC",
          "zh_TW": "MPC",
          "label_value": "MPC"
     },
     {
          "name": "mpcDate",
          "type": "datetime",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "MPC Date Added",
          "cn": "MPC添加日期",
          "zh_TW": "MPC添加日期",
          "label_value": "MPC添加日期"
     },
     {
          "name": "js_is_locked",
          "type": "boolean",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 4,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Candidate Lock",
          "cn": "人才锁定",
          "zh_TW": "人才鎖定",
          "label_value": "人才锁定"
     },
     {
          "name": "owner",
          "type": "foreignkey",
          "view_type": None,
          "options": "user",
          "option_key": None,
          "show": True,
          "default_value": "{{user.id}}",
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": True,
          "to": "user",
          "model": "candidate",
          "en": "Owner",
          "cn": "拥有者",
          "zh_TW": "擁有者",
          "label_value": "拥有者"
     },
     {
          "name": "source",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_source",
                    "code": "gllue",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Manually Add",
                    "zh_CN": "手工录入",
                    "zh_TW": None,
                    "color": "#12859e",
                    "order": 0,
                    "id": 20,
                    "value": "手工录入",
                    "__name__": "手工录入",
                    "__unicode__": "手工录入"
               },
               {
                    "type": "candidate_source",
                    "code": "extension",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Channel Sync",
                    "zh_CN": "渠道同步",
                    "zh_TW": None,
                    "color": "#c0cf69",
                    "order": 1,
                    "id": 21,
                    "value": "渠道同步",
                    "__name__": "渠道同步",
                    "__unicode__": "渠道同步"
               },
               {
                    "type": "candidate_source",
                    "code": "plugin_import",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Extension Import",
                    "zh_CN": "插件导入",
                    "zh_TW": None,
                    "color": "#ff6666",
                    "order": 2,
                    "id": 22,
                    "value": "插件导入",
                    "__name__": "插件导入",
                    "__unicode__": "插件导入"
               },
               {
                    "type": "candidate_source",
                    "code": "excel",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Excel Import",
                    "zh_CN": "Excel导入",
                    "zh_TW": None,
                    "color": "#eda54b",
                    "order": 3,
                    "id": 23,
                    "value": "Excel导入",
                    "__name__": "Excel导入",
                    "__unicode__": "Excel导入"
               },
               {
                    "type": "candidate_source",
                    "code": "mass",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Mass Import",
                    "zh_CN": "批量导入",
                    "zh_TW": None,
                    "color": "#925963",
                    "order": 4,
                    "id": 24,
                    "value": "批量导入",
                    "__name__": "批量导入",
                    "__unicode__": "批量导入"
               },
               {
                    "type": "candidate_source",
                    "code": "email",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Email Sync",
                    "zh_CN": "邮件同步",
                    "zh_TW": None,
                    "color": "#FF37DB",
                    "order": 5,
                    "id": 25,
                    "value": "邮件同步",
                    "__name__": "邮件同步",
                    "__unicode__": "邮件同步"
               },
               {
                    "type": "candidate_source",
                    "code": "campus_public_apply",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Campus Recruiting",
                    "zh_CN": "校园招聘",
                    "zh_TW": None,
                    "color": "#0AFFBD",
                    "order": 6,
                    "id": 26,
                    "value": "校园招聘",
                    "__name__": "校园招聘",
                    "__unicode__": "校园招聘"
               },
               {
                    "type": "candidate_source",
                    "code": "portal",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Portal",
                    "zh_CN": "公司门户",
                    "zh_TW": None,
                    "color": "#3FAFFF",
                    "order": 7,
                    "id": 27,
                    "value": "公司门户",
                    "__name__": "公司门户",
                    "__unicode__": "公司门户"
               },
               {
                    "type": "candidate_source",
                    "code": "maimai",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "MaiMai",
                    "zh_CN": "脉脉",
                    "zh_TW": None,
                    "color": "#3FAFFF",
                    "order": 8,
                    "id": 28,
                    "value": "脉脉",
                    "__name__": "脉脉",
                    "__unicode__": "脉脉"
               },
               {
                    "type": "candidate_source",
                    "code": "wx_applet",
                    "is_buildin": 1,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Weixin Applet",
                    "zh_CN": "微信小程序",
                    "zh_TW": None,
                    "color": "#404172",
                    "order": 9,
                    "id": 1984,
                    "value": "微信小程序",
                    "__name__": "微信小程序",
                    "__unicode__": "微信小程序"
               },
               {
                    "type": "candidate_source",
                    "code": "crm_applet",
                    "is_buildin": 1,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "CRM Applet",
                    "zh_CN": "CRM小程序",
                    "zh_TW": None,
                    "color": "#4285F4",
                    "order": 10,
                    "id": 1985,
                    "value": "CRM小程序",
                    "__name__": "CRM小程序",
                    "__unicode__": "CRM小程序"
               },
               {
                    "type": "candidate_source",
                    "code": "chatbot",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Chatbot",
                    "zh_CN": "对话机器人",
                    "zh_TW": "對話機器人",
                    "color": "#3FAFFF",
                    "order": 11,
                    "id": 1986,
                    "value": "对话机器人",
                    "__name__": "对话机器人",
                    "__unicode__": "对话机器人"
               },
               {
                    "type": "candidate_source",
                    "code": "mesoor",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Mesoor",
                    "zh_CN": "麦穗推荐",
                    "zh_TW": None,
                    "color": "",
                    "order": 12,
                    "id": 1987,
                    "value": "麦穗推荐",
                    "__name__": "麦穗推荐",
                    "__unicode__": "麦穗推荐"
               }
          ],
          "option_key": "candidate_source",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": True,
          "model": "candidate",
          "en": "Entry Way",
          "cn": "录入方式",
          "zh_TW": "錄入方式",
          "label_value": "录入方式"
     },
     {
          "name": "channel",
          "type": "foreignkey",
          "view_type": None,
          "options": "channel",
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": True,
          "to": "channel",
          "model": "candidate",
          "en": "Source",
          "cn": "渠道",
          "zh_TW": "渠道",
          "label_value": "渠道"
     },
     {
          "name": "englishName",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "English Name",
          "cn": "英文名",
          "zh_TW": "英文名",
          "label_value": "英文名"
     },
     {
          "name": "chineseName",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Chinese Name",
          "cn": "中文名",
          "zh_TW": "中文名",
          "label_value": "中文名"
     },
     {
          "name": "gender",
          "type": "boolean",
          "view_type": "radio",
          "options": [
               {
                    "type": "candidate_gender",
                    "code": "true",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Male",
                    "zh_CN": "男",
                    "zh_TW": None,
                    "color": "",
                    "order": 1,
                    "id": 14,
                    "value": "男",
                    "__name__": "男",
                    "__unicode__": "男"
               },
               {
                    "type": "candidate_gender",
                    "code": "false",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Female",
                    "zh_CN": "女",
                    "zh_TW": None,
                    "color": "",
                    "order": 2,
                    "id": 15,
                    "value": "女",
                    "__name__": "女",
                    "__unicode__": "女"
               }
          ],
          "option_key": "candidate_gender",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": True,
          "model": "candidate",
          "en": "Gender",
          "cn": "性别",
          "zh_TW": "性別",
          "label_value": "性别"
     },
     {
          "name": "dateOfBirth",
          "type": "date",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Date of Birth",
          "cn": "生日",
          "zh_TW": "生日",
          "label_value": "生日"
     },
     {
          "name": "address",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Address",
          "cn": "地址",
          "zh_TW": "地址",
          "label_value": "地址"
     },
     {
          "name": "mobile",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Phone",
          "cn": "电话",
          "zh_TW": "電話",
          "label_value": "电话"
     },
     {
          "name": "mobile1",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Work Phone",
          "cn": "工作电话",
          "zh_TW": "工作電話",
          "label_value": "工作电话"
     },
     {
          "name": "mobile2",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Other Phone",
          "cn": "其他电话",
          "zh_TW": "其他電話",
          "label_value": "其他电话"
     },
     {
          "name": "mobile_prefix",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Phone Prefix",
          "cn": "手机区号",
          "zh_TW": "手機區號",
          "label_value": "手机区号"
     },
     {
          "name": "mobile1_prefix",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Work Phone Prefix",
          "cn": "工作电话区号",
          "zh_TW": "工作電話區號",
          "label_value": "工作电话区号"
     },
     {
          "name": "mobile2_prefix",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Other Phone Prefix",
          "cn": "其他电话区号",
          "zh_TW": "其他電話區號",
          "label_value": "其他电话区号"
     },
     {
          "name": "email",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Email",
          "cn": "邮箱",
          "zh_TW": "郵箱",
          "label_value": "邮箱"
     },
     {
          "name": "email1",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Email(Work)",
          "cn": "工作邮件",
          "zh_TW": "工作郵件",
          "label_value": "工作邮件"
     },
     {
          "name": "email2",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 7,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Email(Other)",
          "cn": "其他邮件",
          "zh_TW": "其他郵件",
          "label_value": "其他邮件"
     },
     {
          "name": "wechat",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Wechat",
          "cn": "微信号",
          "zh_TW": "微信號",
          "label_value": "微信号"
     },
     {
          "name": "stature",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Stature",
          "cn": "身高",
          "zh_TW": "身高",
          "label_value": "身高"
     },
     {
          "name": "birth_place",
          "type": "foreignkey",
          "view_type": None,
          "options": "city",
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "to": "city",
          "model": "candidate",
          "en": "Birth Place",
          "cn": "籍贯",
          "zh_TW": "籍貫",
          "label_value": "籍贯"
     },
     {
          "name": "ethnic",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Ethnic",
          "cn": "民族",
          "zh_TW": "民族",
          "label_value": "民族"
     },
     {
          "name": "nationality",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Nationality",
          "cn": "国籍",
          "zh_TW": "國籍",
          "label_value": "国籍"
     },
     {
          "name": "employment_type",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "employment_type",
                    "code": "full_time",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Full Time",
                    "zh_CN": "全职",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": None,
                    "value": "全职",
                    "__name__": "全职",
                    "__unicode__": "全职"
               },
               {
                    "type": "employment_type",
                    "code": "part_time",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Part Time",
                    "zh_CN": "兼职",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": None,
                    "value": "兼职",
                    "__name__": "兼职",
                    "__unicode__": "兼职"
               },
               {
                    "type": "employment_type",
                    "code": "internship",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Internship",
                    "zh_CN": "实习",
                    "zh_TW": None,
                    "color": None,
                    "order": 3,
                    "id": None,
                    "value": "实习",
                    "__name__": "实习",
                    "__unicode__": "实习"
               },
               {
                    "type": "employment_type",
                    "code": "labor_outsourcing",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Labor Outsourcing",
                    "zh_CN": "劳务外包",
                    "zh_TW": None,
                    "color": None,
                    "order": 4,
                    "id": None,
                    "value": "劳务外包",
                    "__name__": "劳务外包",
                    "__unicode__": "劳务外包"
               },
               {
                    "type": "employment_type",
                    "code": "labor_dispatching",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Labor Dispatching",
                    "zh_CN": "劳务派遣",
                    "zh_TW": None,
                    "color": None,
                    "order": 5,
                    "id": None,
                    "value": "劳务派遣",
                    "__name__": "劳务派遣",
                    "__unicode__": "劳务派遣"
               },
               {
                    "type": "employment_type",
                    "code": "rehire_after_retirement",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Rehire After Retirement",
                    "zh_CN": "退休返聘",
                    "zh_TW": None,
                    "color": None,
                    "order": 6,
                    "id": None,
                    "value": "退休返聘",
                    "__name__": "退休返聘",
                    "__unicode__": "退休返聘"
               }
          ],
          "option_key": "employment_type",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Employment Type",
          "cn": "工作性质",
          "zh_TW": "工作性質",
          "label_value": "工作性质"
     },
     {
          "name": "desired_company",
          "type": "text",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Desired Company",
          "cn": "期望公司",
          "zh_TW": "期望公司",
          "label_value": "期望公司"
     },
     {
          "name": "marital_status",
          "type": "char",
          "view_type": "radio",
          "options": [
               {
                    "type": "marital_status",
                    "code": "single",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Single",
                    "zh_CN": "未婚",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": None,
                    "value": "未婚",
                    "__name__": "未婚",
                    "__unicode__": "未婚"
               },
               {
                    "type": "marital_status",
                    "code": "married",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Married",
                    "zh_CN": "已婚",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": None,
                    "value": "已婚",
                    "__name__": "已婚",
                    "__unicode__": "已婚"
               }
          ],
          "option_key": "marital_status",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Martial Status",
          "cn": "婚姻",
          "zh_TW": "婚姻",
          "label_value": "婚姻"
     },
     {
          "name": "political_status",
          "type": "char",
          "view_type": "radio",
          "options": [
               {
                    "type": "political_status",
                    "code": "party_member_of_cpc",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Party Member of CPC",
                    "zh_CN": "中共党员",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": None,
                    "value": "中共党员",
                    "__name__": "中共党员",
                    "__unicode__": "中共党员"
               },
               {
                    "type": "political_status",
                    "code": "probationary_party_member_of_cpc",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Probationary Party Member of CPC",
                    "zh_CN": "中共预备党员",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": None,
                    "value": "中共预备党员",
                    "__name__": "中共预备党员",
                    "__unicode__": "中共预备党员"
               },
               {
                    "type": "political_status",
                    "code": "league_member",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "League member",
                    "zh_CN": "共青团员",
                    "zh_TW": None,
                    "color": None,
                    "order": 3,
                    "id": None,
                    "value": "共青团员",
                    "__name__": "共青团员",
                    "__unicode__": "共青团员"
               },
               {
                    "type": "political_status",
                    "code": "masses",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Masses",
                    "zh_CN": "群众",
                    "zh_TW": None,
                    "color": None,
                    "order": 4,
                    "id": None,
                    "value": "群众",
                    "__name__": "群众",
                    "__unicode__": "群众"
               },
               {
                    "type": "political_status",
                    "code": "democratic_parties",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Democratic Parties",
                    "zh_CN": "民主党派",
                    "zh_TW": None,
                    "color": None,
                    "order": 5,
                    "id": None,
                    "value": "民主党派",
                    "__name__": "民主党派",
                    "__unicode__": "民主党派"
               },
               {
                    "type": "political_status",
                    "code": "others",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Others",
                    "zh_CN": "其他",
                    "zh_TW": None,
                    "color": None,
                    "order": 6,
                    "id": None,
                    "value": "其他",
                    "__name__": "其他",
                    "__unicode__": "其他"
               }
          ],
          "option_key": "political_status",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Political Status",
          "cn": "政治面貌",
          "zh_TW": "政治面貌",
          "label_value": "政治面貌"
     },
     {
          "name": "notice_period",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Notice Period",
          "cn": "离职周期",
          "zh_TW": "离职周期",
          "label_value": "离职周期"
     },
     {
          "name": "lastContactDate",
          "type": "datetime",
          "view_type": "related_time",
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "date_search_items": [
                    "day_range",
                    "today",
                    "this_week",
                    "last_week",
                    "this_month",
                    "last_month",
                    "gte",
                    "lte",
                    "day_gte",
                    "day_lte"
               ]
          },
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Last Contact",
          "cn": "最近联系",
          "zh_TW": "最近聯繫",
          "label_value": "最近联系"
     },
     {
          "name": "dateAdded",
          "type": "datetime",
          "view_type": "datetime",
          "options": None,
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Date Added",
          "cn": "添加日期",
          "zh_TW": "添加日期",
          "label_value": "添加日期"
     },
     {
          "name": "latest_action",
          "type": "datetime",
          "view_type": "related_time",
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Latest Action",
          "cn": "最近操作",
          "zh_TW": "最近操作",
          "label_value": "最近操作"
     },
     {
          "name": "lastContactBy",
          "type": "foreignkey",
          "view_type": None,
          "options": "user",
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "to": "user",
          "model": "candidate",
          "en": "last Contact By",
          "cn": "最近备注者",
          "zh_TW": "最近備註者",
          "label_value": "最近备注者"
     },
     {
          "name": "lastUpdateStatusDate",
          "type": "datetime",
          "view_type": "related_time",
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Last Update Status",
          "cn": "状态变更",
          "zh_TW": "狀態變更",
          "label_value": "状态变更"
     },
     {
          "name": "annualSalary",
          "type": "integer",
          "view_type": "currency",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "unit": "万"
          },
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Annual Salary",
          "cn": "年薪",
          "zh_TW": "年薪",
          "label_value": "年薪"
     },
     {
          "name": "expected_salary",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "unit": "万"
          },
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Exp Salary",
          "cn": "期望薪资",
          "zh_TW": "期望薪資",
          "label_value": "期望薪资"
     },
     {
          "name": "is_deleted",
          "type": "boolean",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 4,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Deleted people",
          "cn": "已删除的人才",
          "zh_TW": "已刪除的人才",
          "label_value": "已删除的人才"
     },
     {
          "name": "recommend_user",
          "type": "foreignkey",
          "view_type": None,
          "options": "glluemeuser",
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "to": "glluemeuser",
          "model": "candidate",
          "en": "Recommend User",
          "cn": "推荐人",
          "zh_TW": "推荐人",
          "label_value": "推荐人"
     },
     {
          "name": "built_in_self_assessment",
          "type": "text",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Self Evaluation",
          "cn": "自我评价",
          "zh_TW": "自我評價",
          "label_value": "自我评价"
     },
     {
          "name": "built_in_expected_industry",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Expected Industry",
          "cn": "期望行业",
          "zh_TW": "期望行業",
          "label_value": "期望行业"
     },
     {
          "name": "built_in_expected_function",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Expected Job",
          "cn": "期望职位",
          "zh_TW": "期望職位",
          "label_value": "期望职位"
     },
     {
          "name": "position_status",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_position_status",
                    "code": "on_job_with_thinking",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Employed and open",
                    "zh_CN": "在职观望",
                    "zh_TW": "在職觀望",
                    "color": "",
                    "order": 0,
                    "id": 769,
                    "value": "在职观望",
                    "__name__": "在职观望",
                    "__unicode__": "在职观望"
               },
               {
                    "type": "candidate_position_status",
                    "code": "on_job_with_finding",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Employed and active",
                    "zh_CN": "在职急寻",
                    "zh_TW": "在職急尋",
                    "color": "",
                    "order": 1,
                    "id": 770,
                    "value": "在职急寻",
                    "__name__": "在职急寻",
                    "__unicode__": "在职急寻"
               },
               {
                    "type": "candidate_position_status",
                    "code": "on_job_with_no_change",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Employed and stable",
                    "zh_CN": "在职稳定",
                    "zh_TW": "在職穩定",
                    "color": "",
                    "order": 2,
                    "id": 771,
                    "value": "在职稳定",
                    "__name__": "在职稳定",
                    "__unicode__": "在职稳定"
               },
               {
                    "type": "candidate_position_status",
                    "code": "on_job",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Employed",
                    "zh_CN": "在职",
                    "zh_TW": "在職",
                    "color": "",
                    "order": 3,
                    "id": 772,
                    "value": "在职",
                    "__name__": "在职",
                    "__unicode__": "在职"
               },
               {
                    "type": "candidate_position_status",
                    "code": "leave",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Unemployed and active",
                    "zh_CN": "离职在找",
                    "zh_TW": "離職在找",
                    "color": "",
                    "order": 4,
                    "id": 773,
                    "value": "离职在找",
                    "__name__": "离职在找",
                    "__unicode__": "离职在找"
               },
               {
                    "type": "candidate_position_status",
                    "code": "graduates",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Graduates",
                    "zh_CN": "应届毕业生",
                    "zh_TW": "應屆畢業生",
                    "color": "",
                    "order": 5,
                    "id": 774,
                    "value": "应届毕业生",
                    "__name__": "应届毕业生",
                    "__unicode__": "应届毕业生"
               }
          ],
          "option_key": "candidate_position_status",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Channel Status",
          "cn": "渠道状态",
          "zh_TW": "渠道狀態",
          "label_value": "渠道状态"
     },
     {
          "name": "position_status_time",
          "type": "datetime",
          "view_type": "date",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Channel Update",
          "cn": "渠道更新",
          "zh_TW": "渠道更新",
          "label_value": "渠道更新"
     },
     {
          "name": "company",
          "type": "foreignkey",
          "view_type": None,
          "options": "client",
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "to": "client",
          "model": "candidate",
          "en": "Company",
          "cn": "公司",
          "zh_TW": "公司",
          "label_value": "公司"
     },
     {
          "name": "title",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": True,
          "model": "candidate",
          "en": "Position",
          "cn": "职位",
          "zh_TW": "職位",
          "label_value": "职位"
     },
     {
          "name": "jobsubmission_count",
          "type": "integer",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Applicant Count",
          "cn": "应聘数量",
          "zh_TW": "应聘数量",
          "label_value": "应聘数量"
     },
     {
          "name": "highest_education",
          "type": "foreignkey",
          "view_type": None,
          "options": "candidateeducation",
          "option_key": None,
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "to": "candidateeducation",
          "model": "candidate",
          "en": "Highest Education",
          "cn": "最高教育经历",
          "zh_TW": "",
          "label_value": "最高教育经历"
     },
     {
          "name": "id_card",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "ID Card",
          "cn": "身份证",
          "zh_TW": "身份證",
          "label_value": "身份证"
     },
     {
          "name": "idCardType",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_idcardtype",
                    "code": "IDENTITY_CARD",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "ID Card",
                    "zh_CN": "身份证",
                    "zh_TW": None,
                    "color": "#54698D",
                    "order": 5,
                    "id": 1723,
                    "value": "身份证",
                    "__name__": "身份证",
                    "__unicode__": "身份证"
               },
               {
                    "type": "candidate_idcardtype",
                    "code": "PASSPORT",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Passport",
                    "zh_CN": "护照",
                    "zh_TW": None,
                    "color": "#54698D",
                    "order": 6,
                    "id": 1724,
                    "value": "护照",
                    "__name__": "护照",
                    "__unicode__": "护照"
               },
               {
                    "type": "candidate_idcardtype",
                    "code": "MILITARY_ID",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Military ID",
                    "zh_CN": "军官证",
                    "zh_TW": None,
                    "color": "#54698D",
                    "order": 7,
                    "id": 1725,
                    "value": "军官证",
                    "__name__": "军官证",
                    "__unicode__": "军官证"
               },
               {
                    "type": "candidate_idcardtype",
                    "code": "MTP",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Mainland Travel Permit for Taiwan Residents (MTP)",
                    "zh_CN": "台胞证",
                    "zh_TW": None,
                    "color": "#54698D",
                    "order": 8,
                    "id": 1726,
                    "value": "台胞证",
                    "__name__": "台胞证",
                    "__unicode__": "台胞证"
               },
               {
                    "type": "candidate_idcardtype",
                    "code": "OTHER",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Other",
                    "zh_CN": "其他",
                    "zh_TW": None,
                    "color": "#54698D",
                    "order": 9,
                    "id": 1727,
                    "value": "其他",
                    "__name__": "其他",
                    "__unicode__": "其他"
               }
          ],
          "option_key": "candidate_idcardtype",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "idCardType",
          "cn": "证件类型",
          "zh_TW": "证件类型",
          "label_value": "证件类型"
     },
     {
          "name": "idCardNo",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "idCardNo",
          "cn": "证件号码",
          "zh_TW": "证件号码",
          "label_value": "证件号码"
     },
     {
          "name": "virtual_mobile",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Virtual Mobile",
          "cn": "虚拟号",
          "zh_TW": "虚拟号",
          "label_value": "虚拟号"
     },
     {
          "name": "authorization_status",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_authorization_status",
                    "code": "INVITED",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Pending",
                    "zh_CN": "授权中",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": None,
                    "value": "授权中",
                    "__name__": "授权中",
                    "__unicode__": "授权中"
               },
               {
                    "type": "candidate_authorization_status",
                    "code": "AUTHORIZED",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Opt-in",
                    "zh_CN": "已授权",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": None,
                    "value": "已授权",
                    "__name__": "已授权",
                    "__unicode__": "已授权"
               },
               {
                    "type": "candidate_authorization_status",
                    "code": "INACTIVE",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Opt-out",
                    "zh_CN": "已拒绝",
                    "zh_TW": None,
                    "color": None,
                    "order": 3,
                    "id": None,
                    "value": "已拒绝",
                    "__name__": "已拒绝",
                    "__unicode__": "已拒绝"
               },
               {
                    "type": "candidate_authorization_status",
                    "code": "EXPIRED",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Expired",
                    "zh_CN": "已失效",
                    "zh_TW": None,
                    "color": None,
                    "order": 4,
                    "id": None,
                    "value": "已失效",
                    "__name__": "已失效",
                    "__unicode__": "已失效"
               },
               {
                    "type": "candidate_authorization_status",
                    "code": "OVERDUE_AUTO_REJECTION",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Auto Opt-out",
                    "zh_CN": "自动拒绝",
                    "zh_TW": None,
                    "color": None,
                    "order": 5,
                    "id": None,
                    "value": "自动拒绝",
                    "__name__": "自动拒绝",
                    "__unicode__": "自动拒绝"
               }
          ],
          "option_key": "candidate_authorization_status",
          "show": 5,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Consent status",
          "cn": "授权状态",
          "zh_TW": "授權狀態",
          "label_value": "授权状态"
     },
     {
          "name": "parent",
          "type": "foreignkey",
          "view_type": None,
          "options": "candidate",
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "disable_inline_edit": True
          },
          "editable": False,
          "facet_able": False,
          "to": "candidate",
          "model": "candidate",
          "en": "Main",
          "cn": "主体",
          "zh_TW": "主體",
          "label_value": "主体"
     },
     {
          "name": "is_parent",
          "type": "integer",
          "view_type": "radio",
          "options": [
               {
                    "type": "candidate_is_parent",
                    "code": "0",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Subordinate",
                    "zh_CN": "附属",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": None,
                    "value": "附属",
                    "__name__": "附属",
                    "__unicode__": "附属"
               },
               {
                    "type": "candidate_is_parent",
                    "code": "1",
                    "is_buildin": True,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": False,
                    "en_US": "Main",
                    "zh_CN": "主体",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": None,
                    "value": "主体",
                    "__name__": "主体",
                    "__unicode__": "主体"
               }
          ],
          "option_key": "candidate_is_parent",
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "disable_inline_edit": True
          },
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Candidate property",
          "cn": "人才属性",
          "zh_TW": "人才屬性",
          "label_value": "人才属性"
     },
     {
          "name": "lastUpdateDate",
          "type": "datetime",
          "view_type": "related_time",
          "options": None,
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "model": "candidate",
          "en": "Lastest Update",
          "cn": "最近更新",
          "zh_TW": "最近更新",
          "label_value": "最近更新"
     },
     {
          "name": "addedBy",
          "type": "foreignkey",
          "view_type": None,
          "options": "user",
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": True,
          "to": "user",
          "model": "candidate",
          "en": "Added By",
          "cn": "添加人",
          "zh_TW": "添加人",
          "label_value": "添加人"
     },
     {
          "name": "lastUpdateBy",
          "type": "foreignkey",
          "view_type": None,
          "options": "user",
          "option_key": None,
          "show": 13,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": False,
          "facet_able": False,
          "to": "user",
          "model": "candidate",
          "en": "Last Update By",
          "cn": "最近更新者",
          "zh_TW": "最近更新者",
          "label_value": "最近更新者"
     },
     {
          "name": "current_salary",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "unit": "万",
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Salary Structure",
          "cn": "目前薪酬",
          "zh_TW": "薪資結構",
          "label_value": "目前薪酬"
     },
     {
          "name": "gllueextadd_date",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextadd_date",
          "cn": "add date of job control",
          "zh_TW": "gllueextadd_date",
          "label_value": "add date of job control"
     },
     {
          "name": "gllueextbgdID",
          "type": "integer",
          "view_type": "integer",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextbgdID",
          "cn": "导入ID",
          "zh_TW": "gllueextbgdID",
          "label_value": "导入ID"
     },
     {
          "name": "gllueextcertificate",
          "type": "char",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextcertificate",
          "cn": "资格认证",
          "zh_TW": "gllueextcertificate",
          "label_value": "资格认证"
     },
     {
          "name": "gllueextClient_report_comments",
          "type": "char",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": "客户报告-备注",
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextClient_report_comments",
          "cn": "客户报告备注",
          "zh_TW": "gllueextClient_report_comments",
          "label_value": "客户报告备注"
     },
     {
          "name": "gllueextCourses",
          "type": "char",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextCourses",
          "cn": "所学课程",
          "zh_TW": "gllueextCourses",
          "label_value": "所学课程"
     },
     {
          "name": "gllueextechengCV",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextechengCV",
          "cn": "e成-CV",
          "zh_TW": "gllueextechengCV",
          "label_value": "e成-CV"
     },
     {
          "name": "gllueextechengeducationEXP",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextechengeducationEXP",
          "cn": "e成-教育经历",
          "zh_TW": "gllueextechengeducationEXP",
          "label_value": "e成-教育经历"
     },
     {
          "name": "gllueextechengworkEXP",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextechengworkEXP",
          "cn": "e成-工作经历",
          "zh_TW": "gllueextechengworkEXP",
          "label_value": "e成-工作经历"
     },
     {
          "name": "gllueextgllueextechengprojectEXP",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextgllueextechengprojectEXP",
          "cn": "e成-项目经历",
          "zh_TW": "gllueextgllueextechengprojectEXP",
          "label_value": "e成-项目经历"
     },
     {
          "name": "gllueextImportData",
          "type": "char",
          "view_type": "radio",
          "options": [
               {
                    "type": "candidate_gllueextImportData",
                    "code": "n53103199735565180",
                    "is_buildin": 0,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": 1,
                    "is_deleted": 0,
                    "en_US": "B",
                    "zh_CN": "B",
                    "zh_TW": None,
                    "color": "",
                    "order": 1,
                    "id": 647,
                    "value": "B",
                    "__name__": "B",
                    "__unicode__": "B"
               },
               {
                    "type": "candidate_gllueextImportData",
                    "code": "n77610961915168200",
                    "is_buildin": 0,
                    "ext": "",
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "G",
                    "zh_CN": "G",
                    "zh_TW": None,
                    "color": "",
                    "order": 2,
                    "id": 668,
                    "value": "G",
                    "__name__": "G",
                    "__unicode__": "G"
               }
          ],
          "option_key": "candidate_gllueextImportData",
          "show": True,
          "default_value": "",
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextImportData",
          "cn": "导入数据",
          "zh_TW": "gllueextImportData",
          "label_value": "导入数据"
     },
     {
          "name": "gllueextoldcity",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextoldcity",
          "cn": "导入城市",
          "zh_TW": "gllueextoldcity",
          "label_value": "导入城市"
     },
     {
          "name": "gllueextoldemail",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextoldemail",
          "cn": "导入邮箱",
          "zh_TW": "gllueextoldemail",
          "label_value": "导入邮箱"
     },
     {
          "name": "gllueextoldfunction",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextoldfunction",
          "cn": "导入职能",
          "zh_TW": "gllueextoldfunction",
          "label_value": "导入职能"
     },
     {
          "name": "gllueextoldindustry",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextoldindustry",
          "cn": "导入行业",
          "zh_TW": "gllueextoldindustry",
          "label_value": "导入行业"
     },
     {
          "name": "gllueextoldmobile",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": None,
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextoldmobile",
          "cn": "导入手机",
          "zh_TW": "gllueextoldmobile",
          "label_value": "导入手机"
     },
     {
          "name": "gllueextPublications",
          "type": "char",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "gllueextPublications",
          "cn": "出版作品",
          "zh_TW": "gllueextPublications",
          "label_value": "出版作品"
     },
     {
          "name": "gllueext_AdditionalInformation",
          "type": "text",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "Additional Information",
          "cn": "附加信息",
          "zh_TW": "附加信息",
          "label_value": "附加信息"
     },
     {
          "name": "gllueext_channelURL",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": "",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "原渠道链接",
          "cn": "原渠道简历",
          "zh_TW": "原渠道链接",
          "label_value": "原渠道简历"
     },
     {
          "name": "gllueext_Consultant_evaluation",
          "type": "char",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": "",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "g",
          "cn": "顾问评价",
          "zh_TW": "g",
          "label_value": "顾问评价"
     },
     {
          "name": "gllueext_jiguan",
          "type": "foreignkey",
          "view_type": "foreignkey",
          "options": "city",
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "to": "city",
          "model": "candidate",
          "en": "籍贯",
          "cn": "籍贯",
          "zh_TW": "籍贯",
          "label_value": "籍贯"
     },
     {
          "name": "gllueext_select_1532920743234",
          "type": "char",
          "view_type": "checkbox",
          "options": [
               {
                    "type": "candidate_gllueext_select_1532920743234",
                    "code": "n73510446985271570",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "手机错误",
                    "zh_CN": "手机错误",
                    "zh_TW": None,
                    "color": "#ffc100",
                    "order": 0,
                    "id": 2352,
                    "value": "手机错误",
                    "__name__": "手机错误",
                    "__unicode__": "手机错误"
               },
               {
                    "type": "candidate_gllueext_select_1532920743234",
                    "code": "n50792497508836010",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "邮箱错误",
                    "zh_CN": "邮箱错误",
                    "zh_TW": None,
                    "color": "#ff5500",
                    "order": 1,
                    "id": 2353,
                    "value": "邮箱错误",
                    "__name__": "邮箱错误",
                    "__unicode__": "邮箱错误"
               },
               {
                    "type": "candidate_gllueext_select_1532920743234",
                    "code": "n30436088335508748",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "简历信息错误",
                    "zh_CN": "简历信息错误",
                    "zh_TW": None,
                    "color": "#ff189f",
                    "order": 2,
                    "id": 2354,
                    "value": "简历信息错误",
                    "__name__": "简历信息错误",
                    "__unicode__": "简历信息错误"
               }
          ],
          "option_key": "candidate_gllueext_select_1532920743234",
          "show": True,
          "default_value": "",
          "help_text": "候选人基础信息错误",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "Invaild",
          "cn": "Invalid",
          "zh_TW": "Invaild",
          "label_value": "Invalid"
     },
     {
          "name": "gllueext_select_1545633721962",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_gllueext_select_1545633721962",
                    "code": "n54347335264703340",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Single",
                    "zh_CN": "未婚",
                    "zh_TW": None,
                    "color": None,
                    "order": 0,
                    "id": 2367,
                    "value": "未婚",
                    "__name__": "未婚",
                    "__unicode__": "未婚"
               },
               {
                    "type": "candidate_gllueext_select_1545633721962",
                    "code": "n62433471554394410",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Married",
                    "zh_CN": "已婚",
                    "zh_TW": None,
                    "color": None,
                    "order": 1,
                    "id": 2368,
                    "value": "已婚",
                    "__name__": "已婚",
                    "__unicode__": "已婚"
               },
               {
                    "type": "candidate_gllueext_select_1545633721962",
                    "code": "n98870360896768860",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Married with child",
                    "zh_CN": "已婚已育",
                    "zh_TW": None,
                    "color": None,
                    "order": 2,
                    "id": 2369,
                    "value": "已婚已育",
                    "__name__": "已婚已育",
                    "__unicode__": "已婚已育"
               },
               {
                    "type": "candidate_gllueext_select_1545633721962",
                    "code": "n66259665772313190",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Divorced",
                    "zh_CN": "离异",
                    "zh_TW": None,
                    "color": None,
                    "order": 3,
                    "id": 2370,
                    "value": "离异",
                    "__name__": "离异",
                    "__unicode__": "离异"
               }
          ],
          "option_key": "candidate_gllueext_select_1545633721962",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "color": False,
               "bilingual": False,
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "Martial Status",
          "cn": "婚姻状况",
          "zh_TW": "婚姻状况",
          "label_value": "婚姻状况"
     },
     {
          "name": "gllueext_select_1596507672887",
          "type": "char",
          "view_type": "radio",
          "options": [
               {
                    "type": "candidate_gllueext_select_1596507672887",
                    "code": "n18682040445321536",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "确证集团战略",
                    "zh_CN": "Yes",
                    "zh_TW": None,
                    "color": "",
                    "order": 0,
                    "id": 1970,
                    "value": "Yes",
                    "__name__": "Yes",
                    "__unicode__": "Yes"
               }
          ],
          "option_key": "candidate_gllueext_select_1596507672887",
          "show": True,
          "default_value": None,
          "help_text": "",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "SVP文档类型",
          "cn": "是否保密人才",
          "zh_TW": "SVP文档类型",
          "label_value": "是否保密人才"
     },
     {
          "name": "gllueext_Summary",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "Summary",
          "cn": "Summary",
          "zh_TW": "Summary",
          "label_value": "Summary"
     },
     {
          "name": "gllueext_text_1524122020001",
          "type": "text",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "顾问评价",
          "cn": "顾问评价",
          "zh_TW": "顾问评价",
          "label_value": "顾问评价"
     },
     {
          "name": "gllueext_text_1530795376068",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "微信号",
          "cn": "微信号",
          "zh_TW": "微信号",
          "label_value": "微信号"
     },
     {
          "name": "gllueext_text_1625106132543",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": "",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "花名",
          "cn": "花名",
          "zh_TW": "花名",
          "label_value": "花名"
     },
     {
          "name": "gllueext_text_1625106216777",
          "type": "text",
          "view_type": "multiline",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": "家庭情况，子女，父母亲等\n婚否？小孩年纪？谁在带？房贷压力，每月还款数；小孩的就学情况",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "家庭婚育情况",
          "cn": "层级",
          "zh_TW": "家庭婚育情况",
          "label_value": "层级"
     },
     {
          "name": "gllueext_text_1625213079378",
          "type": "char",
          "view_type": "char",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": "是否买房、买在哪里？房贷多少",
          "ext_data": {
               "enable_formula": False
          },
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "置业情况",
          "cn": "置业情况",
          "zh_TW": "置业情况",
          "label_value": "置业情况"
     },
     {
          "name": "gllueext_text_miaoshu",
          "type": "text",
          "view_type": "richtext",
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": "",
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": False,
          "ext": True,
          "model": "candidate",
          "en": "详情描述",
          "cn": "详情描述",
          "zh_TW": "详情描述",
          "label_value": "详情描述"
     },
     {
          "name": "glluerw_reportResult",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "investigate_order_reportResult",
                    "code": "0",
                    "is_buildin": 1,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Discrepancy",
                    "zh_CN": "有出入",
                    "zh_TW": None,
                    "color": "#f4c600",
                    "order": 0,
                    "id": 2194,
                    "value": "有出入",
                    "__name__": "有出入",
                    "__unicode__": "有出入"
               },
               {
                    "type": "investigate_order_reportResult",
                    "code": "2",
                    "is_buildin": 1,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Progress",
                    "zh_CN": "进行中",
                    "zh_TW": None,
                    "color": "#bebebe",
                    "order": 1,
                    "id": 2195,
                    "value": "进行中",
                    "__name__": "进行中",
                    "__unicode__": "进行中"
               },
               {
                    "type": "investigate_order_reportResult",
                    "code": "1",
                    "is_buildin": 1,
                    "ext": None,
                    "not_orderable": None,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Normal",
                    "zh_CN": "正常",
                    "zh_TW": None,
                    "color": "#2aa515",
                    "order": 2,
                    "id": 2196,
                    "value": "正常",
                    "__name__": "正常",
                    "__unicode__": "正常"
               }
          ],
          "option_key": "investigate_order_reportResult",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "disable_inline_edit": True
          },
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Reportresult",
          "cn": "背调判灯结果",
          "zh_TW": "總判燈結果",
          "label_value": "背调判灯结果"
     },
     {
          "name": "glluerw_reportUrl",
          "type": "char",
          "view_type": None,
          "options": None,
          "option_key": None,
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {
               "disable_inline_edit": True
          },
          "editable": True,
          "facet_able": False,
          "model": "candidate",
          "en": "Reporturl",
          "cn": "背调报告",
          "zh_TW": "報告鏈接",
          "label_value": "背调报告"
     },
     {
          "name": "status",
          "type": "char",
          "view_type": "dropdown",
          "options": [
               {
                    "type": "candidate_status",
                    "code": "Active",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Active",
                    "zh_CN": "想看机会",
                    "zh_TW": None,
                    "color": "#ff9300",
                    "order": 1,
                    "id": 427,
                    "value": "想看机会",
                    "__name__": "想看机会",
                    "__unicode__": "想看机会"
               },
               {
                    "type": "candidate_status",
                    "code": "Inactive",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Inactive",
                    "zh_CN": "现状稳定",
                    "zh_TW": None,
                    "color": "#a9a9a9",
                    "order": 2,
                    "id": 428,
                    "value": "现状稳定",
                    "__name__": "现状稳定",
                    "__unicode__": "现状稳定"
               },
               {
                    "type": "candidate_status",
                    "code": "Block",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Block",
                    "zh_CN": "黑名单",
                    "zh_TW": None,
                    "color": "#000000",
                    "order": 3,
                    "id": 429,
                    "value": "黑名单",
                    "__name__": "黑名单",
                    "__unicode__": "黑名单"
               },
               {
                    "type": "candidate_status",
                    "code": "Successful",
                    "is_buildin": 1,
                    "ext": "",
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "Successful",
                    "zh_CN": "成功Offer",
                    "zh_TW": None,
                    "color": "#ff7e79",
                    "order": 4,
                    "id": 430,
                    "value": "成功Offer",
                    "__name__": "成功Offer",
                    "__unicode__": "成功Offer"
               },
               {
                    "type": "candidate_status",
                    "code": "n64377265833785490",
                    "is_buildin": 0,
                    "ext": None,
                    "not_orderable": 1,
                    "poset_order": None,
                    "is_deleted": 0,
                    "en_US": "电话空号",
                    "zh_CN": "电话空号",
                    "zh_TW": None,
                    "color": None,
                    "order": 5,
                    "id": 837,
                    "value": "电话空号",
                    "__name__": "电话空号",
                    "__unicode__": "电话空号"
               }
          ],
          "option_key": "candidate_status",
          "show": True,
          "default_value": None,
          "help_text": None,
          "ext_data": {},
          "editable": True,
          "facet_able": True,
          "model": "candidate",
          "en": "Candidate Status",
          "cn": "状态",
          "zh_TW": "狀態",
          "label_value": "状态"
     }
]
_list = []
for i in d:
    _list.append(i.get("type"))
print(set(_list))
