apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sync-gllue-push-candidate-waifu-id
  namespace: tip
spec:
  selector:
    matchLabels:
      app: data-sync-gllue-push-candidate-waifu-id
      version: v1
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: data-sync-gllue-push-candidate-waifu-id
        version: v1
        tier: backend
        track: stable
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: data-sync-gllue-push-candidate-waifu-id
          image: cr.mesoor.com/develop/data-sync-cdc:waifu20231211
          imagePullPolicy: Always
          env:
            - name: PYTHONPATH
              value: "."
            - name: EntityStorageServerHost
              value: "http://data-sync-v2-entity-storage-server"
            - name: ApiServerHost
              value: "https://fsg.gllue.com"
            - name: AesKey
              value: "ce5e7cb4ea88075b"
            - name: Recent
              value: "3"
            - name: Unit
              value: "day"
            - name: Account
              value: "minghui.a.qi@accenture.com"
            - name: SleepTimes
              value: "360"
            - name: TenantAlias
              value: "waifu"
          command: [ "python", "./channel/gllue/executor/push_candidate_tag/run_candidate_by_id.py"]
      imagePullSecrets:
        - name: crmesoor-pullsecret
