version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: wurstmeister/kafka:latest
    ports:
     - 9092:9092
     - 3030:3030
    links:
     - zookeeper
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
     - KAFKA_CREATE_TOPICS=postgres.public.notes:1:1

  postgres:
    image: postgres:latest
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  connect:
    image: debezium/connect:latest
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092