apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sync-route-server
  namespace: tip
spec:
  selector:
    matchLabels:
      app: data-sync-route-server
      version: v1
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: data-sync-route-server
        version: v1
        tier: backend
        track: stable
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: data-sync-route-server
          image: cr.mesoor.com/production/data-sync-cdc:v20230913-01
          imagePullPolicy: Always
          env:
            - name: PYTHONPATH
              value: "."
            - name: TRANSMITTER_HOST
              value: "http://dev-ruleengine"
          command: [ "python", "./fuzeRouteServer/server.py"]
      imagePullSecrets:
        - name: crmesoor-pullsecret
