map = {}

_industry_list = [
        {
            "name": "互联网/IT/电子/通信",
            "id": 67,
            "name_en": "",
            "name_zh_tw": "",
            "order": 1,
            "parent_id": None,
            "label": "互联网/IT/电子/通信",
            "__name__": "互联网/IT/电子/通信",
            "another_label": "",
            "children": [
                {
                    "name": "电子商务",
                    "id": 68,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 67,
                    "label": "电子商务",
                    "__name__": "电子商务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "游戏",
                    "id": 69,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 67,
                    "label": "游戏",
                    "__name__": "游戏",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "媒体",
                    "id": 70,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 67,
                    "label": "媒体",
                    "__name__": "媒体",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "广告营销",
                    "id": 71,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 67,
                    "label": "广告营销",
                    "__name__": "广告营销",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "数据服务",
                    "id": 72,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 67,
                    "label": "数据服务",
                    "__name__": "数据服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "医疗健康",
                    "id": 73,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 67,
                    "label": "医疗健康",
                    "__name__": "医疗健康",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "生活服务",
                    "id": 74,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 67,
                    "label": "生活服务",
                    "__name__": "生活服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "O2O",
                    "id": 75,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 8,
                    "parent_id": 67,
                    "label": "O2O",
                    "__name__": "O2O",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "旅游",
                    "id": 76,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 9,
                    "parent_id": 67,
                    "label": "旅游",
                    "__name__": "旅游",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "分类信息",
                    "id": 77,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 10,
                    "parent_id": 67,
                    "label": "分类信息",
                    "__name__": "分类信息",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "音乐/视频/阅读",
                    "id": 78,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 11,
                    "parent_id": 67,
                    "label": "音乐/视频/阅读",
                    "__name__": "音乐/视频/阅读",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "在线教育",
                    "id": 79,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 12,
                    "parent_id": 67,
                    "label": "在线教育",
                    "__name__": "在线教育",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "社交网络",
                    "id": 80,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 13,
                    "parent_id": 67,
                    "label": "社交网络",
                    "__name__": "社交网络",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "人力资源服务",
                    "id": 81,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 14,
                    "parent_id": 67,
                    "label": "人力资源服务",
                    "__name__": "人力资源服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "企业服务",
                    "id": 82,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 15,
                    "parent_id": 67,
                    "label": "企业服务",
                    "__name__": "企业服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "信息安全",
                    "id": 83,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 16,
                    "parent_id": 67,
                    "label": "信息安全",
                    "__name__": "信息安全",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "新零售",
                    "id": 84,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 17,
                    "parent_id": 67,
                    "label": "新零售",
                    "__name__": "新零售",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "智能硬件",
                    "id": 85,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 18,
                    "parent_id": 67,
                    "label": "智能硬件",
                    "__name__": "智能硬件",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "移动互联网",
                    "id": 86,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 19,
                    "parent_id": 67,
                    "label": "移动互联网",
                    "__name__": "移动互联网",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "互联网",
                    "id": 87,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 20,
                    "parent_id": 67,
                    "label": "互联网",
                    "__name__": "互联网",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "计算机软件",
                    "id": 88,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 21,
                    "parent_id": 67,
                    "label": "计算机软件",
                    "__name__": "计算机软件",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "计算机硬件",
                    "id": 89,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 22,
                    "parent_id": 67,
                    "label": "计算机硬件",
                    "__name__": "计算机硬件",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "计算机服务",
                    "id": 90,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 23,
                    "parent_id": 67,
                    "label": "计算机服务",
                    "__name__": "计算机服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "通信/网络设备",
                    "id": 91,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 24,
                    "parent_id": 67,
                    "label": "通信/网络设备",
                    "__name__": "通信/网络设备",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "运营商/增值服务",
                    "id": 92,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 25,
                    "parent_id": 67,
                    "label": "运营商/增值服务",
                    "__name__": "运营商/增值服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "电子/半导体/集成电路",
                    "id": 93,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 26,
                    "parent_id": 67,
                    "label": "电子/半导体/集成电路",
                    "__name__": "电子/半导体/集成电路",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "消费电子",
                    "id": 94,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 27,
                    "parent_id": 67,
                    "label": "消费电子",
                    "__name__": "消费电子",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "广告/传媒/文化/体育",
            "id": 95,
            "name_en": "",
            "name_zh_tw": "",
            "order": 2,
            "parent_id": None,
            "label": "广告/传媒/文化/体育",
            "__name__": "广告/传媒/文化/体育",
            "another_label": "",
            "children": [
                {
                    "name": "广告/公关/会展",
                    "id": 96,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 95,
                    "label": "广告/公关/会展",
                    "__name__": "广告/公关/会展",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "新闻/出版",
                    "id": 97,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 95,
                    "label": "新闻/出版",
                    "__name__": "新闻/出版",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "广播/影视",
                    "id": 98,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 95,
                    "label": "广播/影视",
                    "__name__": "广播/影视",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "文化/体育/娱乐",
                    "id": 99,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 95,
                    "label": "文化/体育/娱乐",
                    "__name__": "文化/体育/娱乐",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "金融",
            "id": 100,
            "name_en": "",
            "name_zh_tw": "",
            "order": 3,
            "parent_id": None,
            "label": "金融",
            "__name__": "金融",
            "another_label": "",
            "children": [
                {
                    "name": "银行",
                    "id": 101,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 100,
                    "label": "银行",
                    "__name__": "银行",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "保险",
                    "id": 102,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 100,
                    "label": "保险",
                    "__name__": "保险",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "证券/期货",
                    "id": 103,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 100,
                    "label": "证券/期货",
                    "__name__": "证券/期货",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "基金",
                    "id": 104,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 100,
                    "label": "基金",
                    "__name__": "基金",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "信托",
                    "id": 105,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 100,
                    "label": "信托",
                    "__name__": "信托",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "互联网金融",
                    "id": 106,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 100,
                    "label": "互联网金融",
                    "__name__": "互联网金融",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "投资/融资",
                    "id": 107,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 100,
                    "label": "投资/融资",
                    "__name__": "投资/融资",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "租赁/拍卖/典当/担保",
                    "id": 108,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 8,
                    "parent_id": 100,
                    "label": "租赁/拍卖/典当/担保",
                    "__name__": "租赁/拍卖/典当/担保",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "教育培训",
            "id": 109,
            "name_en": "",
            "name_zh_tw": "",
            "order": 4,
            "parent_id": None,
            "label": "教育培训",
            "__name__": "教育培训",
            "another_label": "",
            "children": [
                {
                    "name": "学前教育",
                    "id": 110,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 109,
                    "label": "学前教育",
                    "__name__": "学前教育",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "院校",
                    "id": 112,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 109,
                    "label": "院校",
                    "__name__": "院校",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "培训机构",
                    "id": 113,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 109,
                    "label": "培训机构",
                    "__name__": "培训机构",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "学术/科研",
                    "id": 114,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 109,
                    "label": "学术/科研",
                    "__name__": "学术/科研",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "制药/医疗",
            "id": 115,
            "name_en": "",
            "name_zh_tw": "",
            "order": 5,
            "parent_id": None,
            "label": "制药/医疗",
            "__name__": "制药/医疗",
            "another_label": "",
            "children": [
                {
                    "name": "制药",
                    "id": 116,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 115,
                    "label": "制药",
                    "__name__": "制药",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "医疗/护理/卫生",
                    "id": 117,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 115,
                    "label": "医疗/护理/卫生",
                    "__name__": "医疗/护理/卫生",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "医疗设备/器械",
                    "id": 118,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 115,
                    "label": "医疗设备/器械",
                    "__name__": "医疗设备/器械",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "交通/物流/贸易/零售",
            "id": 119,
            "name_en": "",
            "name_zh_tw": "",
            "order": 6,
            "parent_id": None,
            "label": "交通/物流/贸易/零售",
            "__name__": "交通/物流/贸易/零售",
            "another_label": "",
            "children": [
                {
                    "name": "交通/运输",
                    "id": 120,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 119,
                    "label": "交通/运输",
                    "__name__": "交通/运输",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "物流/仓储",
                    "id": 121,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 119,
                    "label": "物流/仓储",
                    "__name__": "物流/仓储",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "批发/零售",
                    "id": 122,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 119,
                    "label": "批发/零售",
                    "__name__": "批发/零售",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "贸易/进出口",
                    "id": 123,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 119,
                    "label": "贸易/进出口",
                    "__name__": "贸易/进出口",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "专业服务",
            "id": 124,
            "name_en": "",
            "name_zh_tw": "",
            "order": 7,
            "parent_id": None,
            "label": "专业服务",
            "__name__": "专业服务",
            "another_label": "",
            "children": [
                {
                    "name": "咨询",
                    "id": 125,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 124,
                    "label": "咨询",
                    "__name__": "咨询",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "法律",
                    "id": 126,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 124,
                    "label": "法律",
                    "__name__": "法律",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "翻译",
                    "id": 127,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 124,
                    "label": "翻译",
                    "__name__": "翻译",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "人力资源服务",
                    "id": 128,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 124,
                    "label": "人力资源服务",
                    "__name__": "人力资源服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "财务/审计/税务",
                    "id": 129,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 124,
                    "label": "财务/审计/税务",
                    "__name__": "财务/审计/税务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "检测/认证",
                    "id": 131,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 124,
                    "label": "检测/认证",
                    "__name__": "检测/认证",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "专利/商标/知识产权",
                    "id": 132,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 124,
                    "label": "专利/商标/知识产权",
                    "__name__": "专利/商标/知识产权",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "其他专业服务",
                    "id": 133,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 8,
                    "parent_id": 124,
                    "label": "其他专业服务",
                    "__name__": "其他专业服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "房地产/建筑",
            "id": 134,
            "name_en": "",
            "name_zh_tw": "",
            "order": 8,
            "parent_id": None,
            "label": "房地产/建筑",
            "__name__": "房地产/建筑",
            "another_label": "",
            "children": [
                {
                    "name": "房地产开发",
                    "id": 135,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 134,
                    "label": "房地产开发",
                    "__name__": "房地产开发",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "工程施工",
                    "id": 136,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 134,
                    "label": "工程施工",
                    "__name__": "工程施工",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "建筑设计",
                    "id": 137,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 134,
                    "label": "建筑设计",
                    "__name__": "建筑设计",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "装修装饰",
                    "id": 138,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 134,
                    "label": "装修装饰",
                    "__name__": "装修装饰",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "建材",
                    "id": 139,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 134,
                    "label": "建材",
                    "__name__": "建材",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "地产经纪/中介",
                    "id": 140,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 134,
                    "label": "地产经纪/中介",
                    "__name__": "地产经纪/中介",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "物业服务",
                    "id": 141,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 134,
                    "label": "物业服务",
                    "__name__": "物业服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "汽车",
            "id": 142,
            "name_en": "",
            "name_zh_tw": "",
            "order": 9,
            "parent_id": None,
            "label": "汽车",
            "__name__": "汽车",
            "another_label": "",
            "children": [
                {
                    "name": "汽车生产",
                    "id": 143,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 142,
                    "label": "汽车生产",
                    "__name__": "汽车生产",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "汽车零部件",
                    "id": 144,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 142,
                    "label": "汽车零部件",
                    "__name__": "汽车零部件",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "4S店/后市场",
                    "id": 145,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 142,
                    "label": "4S店/后市场",
                    "__name__": "4S店/后市场",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "机械/制造",
            "id": 146,
            "name_en": "",
            "name_zh_tw": "",
            "order": 10,
            "parent_id": None,
            "label": "机械/制造",
            "__name__": "机械/制造",
            "another_label": "",
            "children": [
                {
                    "name": "机械设备/机电/重工",
                    "id": 147,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 146,
                    "label": "机械设备/机电/重工",
                    "__name__": "机械设备/机电/重工",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "仪器仪表/工业自动化",
                    "id": 148,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 146,
                    "label": "仪器仪表/工业自动化",
                    "__name__": "仪器仪表/工业自动化",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "原材料及加工/模具",
                    "id": 149,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 146,
                    "label": "原材料及加工/模具",
                    "__name__": "原材料及加工/模具",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "印刷/包装/造纸",
                    "id": 151,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 146,
                    "label": "印刷/包装/造纸",
                    "__name__": "印刷/包装/造纸",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "船舶/航空/航天",
                    "id": 152,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 146,
                    "label": "船舶/航空/航天",
                    "__name__": "船舶/航空/航天",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "消费品",
            "id": 153,
            "name_en": "",
            "name_zh_tw": "",
            "order": 11,
            "parent_id": None,
            "label": "消费品",
            "__name__": "消费品",
            "another_label": "",
            "children": [
                {
                    "name": "食品/饮料/烟酒",
                    "id": 154,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 153,
                    "label": "食品/饮料/烟酒",
                    "__name__": "食品/饮料/烟酒",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "日化",
                    "id": 155,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 153,
                    "label": "日化",
                    "__name__": "日化",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "服装/纺织/皮革",
                    "id": 156,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 153,
                    "label": "服装/纺织/皮革",
                    "__name__": "服装/纺织/皮革",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "家具/家电/家居",
                    "id": 157,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 153,
                    "label": "家具/家电/家居",
                    "__name__": "家具/家电/家居",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "玩具/礼品",
                    "id": 159,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 153,
                    "label": "玩具/礼品",
                    "__name__": "玩具/礼品",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "珠宝/首饰",
                    "id": 160,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 153,
                    "label": "珠宝/首饰",
                    "__name__": "珠宝/首饰",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "工艺品/收藏品",
                    "id": 161,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 153,
                    "label": "工艺品/收藏品",
                    "__name__": "工艺品/收藏品",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "办公用品及设备",
                    "id": 162,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 8,
                    "parent_id": 153,
                    "label": "办公用品及设备",
                    "__name__": "办公用品及设备",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "服务业",
            "id": 164,
            "name_en": "",
            "name_zh_tw": "",
            "order": 12,
            "parent_id": None,
            "label": "服务业",
            "__name__": "服务业",
            "another_label": "",
            "children": [
                {
                    "name": "餐饮",
                    "id": 165,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 164,
                    "label": "餐饮",
                    "__name__": "餐饮",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "酒店",
                    "id": 166,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 164,
                    "label": "酒店",
                    "__name__": "酒店",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "旅游",
                    "id": 167,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 164,
                    "label": "旅游",
                    "__name__": "旅游",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "美容/美发",
                    "id": 168,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 164,
                    "label": "美容/美发",
                    "__name__": "美容/美发",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "婚庆/摄影",
                    "id": 169,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 164,
                    "label": "婚庆/摄影",
                    "__name__": "婚庆/摄影",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "休闲/娱乐",
                    "id": 171,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 164,
                    "label": "休闲/娱乐",
                    "__name__": "休闲/娱乐",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "回收/维修",
                    "id": 172,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 164,
                    "label": "回收/维修",
                    "__name__": "回收/维修",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "家政服务",
                    "id": 173,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 8,
                    "parent_id": 164,
                    "label": "家政服务",
                    "__name__": "家政服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "宠物服务",
                    "id": 174,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 9,
                    "parent_id": 164,
                    "label": "宠物服务",
                    "__name__": "宠物服务",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "其他服务业",
                    "id": 170,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 10,
                    "parent_id": 164,
                    "label": "其他服务业",
                    "__name__": "其他服务业",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "能源/化工/环保",
            "id": 175,
            "name_en": "",
            "name_zh_tw": "",
            "order": 13,
            "parent_id": None,
            "label": "能源/化工/环保",
            "__name__": "能源/化工/环保",
            "another_label": "",
            "children": [
                {
                    "name": "石油/石化",
                    "id": 177,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 175,
                    "label": "石油/石化",
                    "__name__": "石油/石化",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "化工",
                    "id": 178,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 175,
                    "label": "化工",
                    "__name__": "化工",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "矿产/地质",
                    "id": 179,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 175,
                    "label": "矿产/地质",
                    "__name__": "矿产/地质",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "采掘/冶炼",
                    "id": 181,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 175,
                    "label": "采掘/冶炼",
                    "__name__": "采掘/冶炼",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "电力/热力/燃气/水利",
                    "id": 182,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 5,
                    "parent_id": 175,
                    "label": "电力/热力/燃气/水利",
                    "__name__": "电力/热力/燃气/水利",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "新能源",
                    "id": 183,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 6,
                    "parent_id": 175,
                    "label": "新能源",
                    "__name__": "新能源",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "环保",
                    "id": 184,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 7,
                    "parent_id": 175,
                    "label": "环保",
                    "__name__": "环保",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "政府/非盈利机构/其他",
            "id": 185,
            "name_en": "",
            "name_zh_tw": "",
            "order": 14,
            "parent_id": None,
            "label": "政府/非盈利机构/其他",
            "__name__": "政府/非盈利机构/其他",
            "another_label": "",
            "children": [
                {
                    "name": "政府/公共事业",
                    "id": 187,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 1,
                    "parent_id": 185,
                    "label": "政府/公共事业",
                    "__name__": "政府/公共事业",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "非盈利机构",
                    "id": 188,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 2,
                    "parent_id": 185,
                    "label": "非盈利机构",
                    "__name__": "非盈利机构",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "农/林/牧/渔",
                    "id": 189,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 3,
                    "parent_id": 185,
                    "label": "农/林/牧/渔",
                    "__name__": "农/林/牧/渔",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                },
                {
                    "name": "其他行业",
                    "id": 190,
                    "name_en": "",
                    "name_zh_tw": "",
                    "order": 4,
                    "parent_id": 185,
                    "label": "其他行业",
                    "__name__": "其他行业",
                    "another_label": "",
                    "children": [],
                    "count": 0,
                    "level": 1
                }
            ],
            "count": 0,
            "level": 0
        },
        {
            "name": "其他",
            "id": 25,
            "name_en": "Others",
            "name_zh_tw": None,
            "order": 15,
            "parent_id": None,
            "label": "其他",
            "__name__": "其他",
            "another_label": "Others",
            "children": [],
            "count": 0,
            "level": 0
        }
    ]
for i in _industry_list:
    map[i["name"]] = i["id"]
    for _ in i.get("children", []):
        lv_2_name = _["name"]
        map[i["name"]+"-" + lv_2_name] = _["id"]
print(map)